- type: entity
  parent: CratePlastic
  id: CrateServiceJanitorialSupplies
  name: ящик з прибиральницьким приладдям
  description: Боріться з брудом та сміттям за допомогою набору "Базові Засоби Прибиральника Нанотрейзен™"! Містить три відра, знаки "мокра підлоги" та чинади. Також є швабра, спрей з очищувачем, дротяна щітка та сміттєвий пакет. "НЕ ХОДИТИ ПО ПОМИТОМУ!!!"
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: MopItem
        - id: MopBucketCubeWrapped
        - id: Bucket
          amount: 3
        - id: WetFloorSign
          amount: 2
        - id: Soap
        - id: SprayBottleSpaceCleaner
          amount: 2
        - id: TrashBag
          amount: 2
        - id: Plunger
          amount: 2
        - id: BoxCleanerGrenades
        - id: WireBrush
          amount: 2

- type: entity
  parent: CratePlastic
  id: CrateServiceCleanerGrenades
  name: оптовий ящик з чинадами
  description: Містить у собі дві коробки чинад (чисто-гранати), для глибоко в'їдених плям. "Це вже якийсь прибиральницький терор."
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxCleanerGrenades
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceReplacementLights
  name: ящик з лампочками
  description: Нехай світло штучної Сатії осяє цю станцію! Або, принаймні, світло дванадцяти трубчасти ламп та стількох ж лампочок. Не давайте це ніанам, не впевнившись, що вони емоційно стабільні.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLighttube
        - id: BoxLightbulb

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceColorfulLights
  name: ящик з різнокольоровими лампочками
  description: Це не вечірка, поки на ній ще щось видно, а вуха не болять. Не давайте це різнокольоровим ніанам, не впевнившись, що вони емоційно стабільні.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLightbulbColorfulMixed
        - id: BoxLighttubeColorfulMixed

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceHolidayLights
  name: ящик з святковими лампочками
  description: "\"Свято наближається - Свято наближається!\" Прикрасьте станцію комбінацією червоно-зеленого світла спеціально напередодні свята! Не давайте це святковим ніанам, не впевнившись, що вони емоційно стабільні."
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxLighttubeHoliday
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateMousetrapBoxes
  name: ящик з мишоловками
  description: Мишоловки, на випадок, коли навала пацюків атакує сервіс. Використовуйте економно... Або ні.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxMousetrap

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceSmokeables
  name: ящик з куривом
  description: Втомилися від швидкої смерті на станції? Замовте цей ящик й пришвидшити процес! "Я б пройшов милю заради цигарки." Заборонено продаж особам молодшим за 18 років, а також вкрай не рекомендується до вживання вагітним жінкам, людям з серцевими захворюваннями, астмою або будь-якими іншими респіраторними захворюваннями.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:GroupSelector
          children:
          - id: CigCartonGreen
            weight: 0.50
          - id: CigCartonRed
        - !type:GroupSelector
          children:
          - id: CigCartonBlue
            weight: 0.50
          - id: CigCartonBlack
        - !type:GroupSelector
          children:
          - id: CigarGoldCase
            weight: 0.05
          - id: CigarCase
        - id: Matchbox
          amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceTheatre
  name: ящик з театральним приладдям
  description: "Містить плащ молі, ножиці перукаря, форму покоївки, атрибути клоуна та міма, а також інші штуки для виступу. Пам'ятайте: \"Весь світ - це театр, а люди в ньому - актори.\""
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: ClothingUniformJumpskirtPerformer
        - id: ClothingShoesBootsPerformer
        - id: ClothingHeadPerformerWig
        - id: ClothingOuterSuitMonkey
        - id: ClothingHeadHatAnimalMonkey
        - id: ClothingNeckCloakMoth
        - id: ClothingMaskClown
        - id: ClothingMaskMime
        - id: ClothingShoesClown
        - id: ClothingUniformJumpskirtJanimaid
        - id: ClothingNeckCloakVoid
        - id: RevolverCapGun
        - id: BarberScissors
        - id: ClothingUniformJumpskirtOldDress
        - id: BikeHorn
        - id: ClownRecorder
        - id: ClothingBeltSuspendersRed
        - id: ClothingBeltSuspendersBlack

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceCustomSmokable
  name: ящик з куривом "Зроби це сам"
  description: Хочете проявити трохи креативності з тим, що ви використовуєте, щоб знищити свої легені? Тоді цей ящик для вас! У ньому є все необхідне, щоб крутити цигарки самостійно. Заборонено продаж особам молодшим за 18 років, а також вкрай не рекомендується до вживання вагітним жінкам, людям з серцевими захворюваннями, астмою або будь-якими іншими респіраторними захворюваннями.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: PackPaperRolling
        - id: CigaretteFilter
          amount: 8
        - id: GroundTobacco
          amount: 4
        - id: SmokingPipe
        - id: Matchbox

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBureaucracy
  name: ящик з бюрократією
  description: Кілька стопок паперу, кілька ручок, папочок, коробочок, етекитувальник, знак brb та прекрасна офісна іграшка. Чого ще бажати справжньому офісному клерку?
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: Paper
          amount: 12
        - id: PaperOffice
          amount: 6
        - id: Pen
          amount: 2
        - id: BoxFolderClipboardEmpty
          amount: 2
        - id: HandLabeler
        - id: BoxFolderBlueEmpty
        - id: BoxFolderRedEmpty
        - id: BoxFolderYellowEmpty
        - id: NewtonCradle
        - id: BoxEnvelope
        - id: BrbSign

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceFaxMachine
  name: ящик з факсом
  description: Факс і викрутка. Друге, щоб дати першому ім'я. Чому просто не змусити заповнити форму на надання назви, яку оброблять протягом 5 робочих днів?
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: Screwdriver
        - id: FaxMachineFlatpack

- type: entity
  parent: CrateCommandSecure
  id: CrateServicePersonnel
  name: ящик з ідентифікаційним обладнанням
  description: Містить у собі коробки з чистими ID-картками та КПК. Де ви знайшли стільки осіб без посвідчень особи?..
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxPDA
        - id: BoxID

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBooks
  name: ящик з книгами
  description: Містить 10 порожніх книг з випадковими обкладинками. Ідеально підходить для ведення щоденників або створення власних шедеврів літератури.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BookRandom
        amount: 10

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceGuidebooks
  name: ящик з посібниками
  description: Містить у собі всі офіційно одобрені Нанотрейзен посібники. Час дізнатися щось нове та (можливо) корисне!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BookSpaceEncyclopedia
        - id: BookTheBookOfControl
        - id: BookBartendersManual
        - id: BookHowToCookForFortySpaceman
        - id: BookLeafLoversSecret
        - id: BookEngineersHandbook
        - id: BookScientistsGuidebook
        - id: BookSecurity
        - id: BookHowToKeepStationClean
        - id: BookHowToRockAndStone
        - id: BookMedicalReferenceBook
        - id: BookHowToSurvive
        - id: BookChemicalCompendium
        - id: BookSpaceLaw

- type: entity
  parent: CrateFreezer
  id: CrateServiceSodaDispenser
  name: ящик з поповненням для дозатора газованки
  description: Містить у собі повний комплект напоїв для дозаторів газованої води. Ви випили все початкове? Час замінити!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: DrinkCoffeeJug
        - id: DrinkColaBottleFull
        - id: DrinkCreamCartonXL
        - id: DrinkDrGibbJug
        - id: DrinkEnergyDrinkJug
        - id: DrinkGreenTeaJug
        - id: DrinkIceJug
        - id: DrinkJuiceLimeCartonXL
        - id: DrinkJuiceOrangeCartonXL
        - id: DrinkLemonLimeJug
        - id: DrinkRootBeerJug
        - id: DrinkSodaWaterBottleFull
        - id: DrinkSpaceMountainWindBottleFull
        - id: DrinkSpaceUpBottleFull
        - id: DrinkSugarJug
        - id: DrinkTeaJug
        - id: DrinkTonicWaterBottleFull
        - id: DrinkWaterMelonJuiceJug

- type: entity
  parent: CrateFreezer
  id: CrateServiceBoozeDispenser
  name: ящик з поповненням для дозатора алкоголю
  description: Містить у собі повний комплект напоїв для дозаторів алкоголю. Ви випили все початкове? (Досить пити) Час замінити!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: DrinkAleBottleFullGrowler
        - id: DrinkBeerGrowler
        - id: DrinkCoffeeLiqueurBottleFull
        - id: DrinkCognacBottleFull
        - id: DrinkGinBottleFull
        - id: DrinkMeadJug
        - id: DrinkRumBottleFull
        - id: DrinkTequilaBottleFull
        - id: DrinkVermouthBottleFull
        - id: DrinkVodkaBottleFull
        - id: DrinkWhiskeyBottleFull
        - id: DrinkWineBottleFull

- type: entity
  parent: CratePlastic
  id: CrateServiceBox
  name: ящик з коробками
  description: Містить у собі 6 порожніх багатоцільових коробок.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxCardboard
        amount: 6

- type: entity
  parent: CratePlastic
  id: CrateJanitorBiosuit
  name: ящик з костюмами біозахисту прибиральників
  description: Містить у собі 2 костюми біологічного захисту, щоб жодна хвороба чи калюжа кислоти не заваодила прибиранню станції.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillBiohazardGearJanitor
          rolls: 2
        - id: ClothingMaskSterile
          amount: 2

- type: entity
  parent: CrateTrashCart
  id: CrateTrashCartFilled
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
          # Creatures
        - id: MobCockroach
          prob: 0.05
        - id: MobMothroach
          prob: 0.03
        - id: MobMouse
          prob: 0.05
          # Food Packaging
        - id: FoodPacketBoritosTrash
          prob: 0.1
        - id: FoodPacketCheesieTrash
          prob: 0.1
        - id: FoodPacketChipsTrash
          prob: 0.1
        - id: FoodPacketSusTrash
          prob: 0.1
        - id: FoodPacketSyndiTrash
          prob: 0.1
        - id: FoodPacketChowMeinTrash
          prob: 0.1
        - id: FoodPacketDanDanTrash
          prob: 0.1
        - id: FoodPacketMRETrash
          prob: 0.1
        - id: FoodPacketPistachioTrash
          prob: 0.1
        - id: FoodPacketSemkiTrash
          prob: 0.1
        - id: FoodPacketRaisinsTrash
          prob: 0.1
          # Cans
        - id: FoodTinBeansTrash
          prob: 0.15
        - id: FoodTinPeachesTrash
          prob: 0.15
        - id: FoodTinMRETrash
          prob: 0.15
          # Cigarette Stuff
        - id: Ash
          prob: 0.15
        - id: CigaretteSpent
          prob: 0.15
          # Bacteria
        - id: FoodBreadMoldySlice
          prob: 0.15
        - id: FoodPizzaMoldySlice
          prob: 0.15
          # Botanical Waste
        - id: TrashBananaPeel
          prob: 0.15
        - id: FoodCornTrash
          prob: 0.15
          # Misc
        - id: DrinkGlass
          prob: 0.15
        - id: BrokenBottle
          prob: 0.15
        - id: LightTubeBroken
          prob: 0.15
        - id: LightBulbBroken
          prob: 0.15
        - id: MobMouseDead
          prob: 0.1
        - id: Syringe
          prob: 0.1
        - id: ShardGlassPlasma
          prob: 0.1

- type: entity
  parent: CrateGenericSteel
  id: CrateCandles
  name: ящик з свічками
  description: Містить 4 коробки свічок - 2 з великими та 2 з маленькими. Для створення атмосфери чи чогось такого. Пам'ятайте, вогонь гарячий.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxCandle
          amount: 2
        - id: BoxCandleSmall
          amount: 2
